spring:
  security:
    user:
      name: 
      password: 
  application:
    name: axle
  datasource:
    url: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    db-kind: mysql
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
      format_sql=true: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification_group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

token:
  expiration-time-ms: 28800000  # 8 hours in milliseconds
mail:
  host:
  port:
  username:
  password:
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
image:
  storage:
    path: uploads/images

management:
  endpoints:
    web:
      exposure:
        include: "*"
