spring:
  security:
    user:
      name: user
      password: user
  application:
    name: haul
  datasource:
    url: jdbc:mysql://localhost:3306/axle_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    db-kind: mysql
    username: root
    password: UWO@nwonknu
  jpa:
    hibernate:
      ddl-auto: update
      format_sql=true: true
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: edupablo72@gmail.com
    password: ezwn xjyt gwrq agsd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

